name: vouched_flutter
description: Vouched Plugin for Flutter.
version: 0.2.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.acmesoftware.vouched
        pluginClass: VouchedPlugin
      ios:
        pluginClass: VouchedFlutterPlugin